### ISSUE TITLE
settings upload *file* error

### ISSUE THREAD

**Issue by igradyyy** [HarutoHiroki/Discord.js-Bot#10]
I got the bot set up and working - but when I attempt to upload the .json file I t=get the following error 

Command: a!settings - Guild: Grand Empire of The Boys ID: 658039225408815141
Done Downloading
(node:9688) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token | in JSON at position 67
    at JSON.parse (<anonymous>)
    at WriteStream.<anonymous> (C:\Users\inequaldev\Desktop\Discord.js-Bot-master\commands\settings.js:24:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HarutoHiroki** [comment]
First of all please read your error messages, it says everything
Second of all please learn how a json file works
Last but not least if you're too lazy just have a look through the example.json I already included
(Tldr: you formatted your json file wrong, this is not a problem with my code)

**Comment by KuroDonut** [comment]
found the issue, thank u
