### ISSUE TITLE
Bot not working on command

### ISSUE THREAD

**Issue by KuroDonut** [HarutoHiroki/Discord.js-Bot#11]
All commands dont work i do !help but it tells me to do !settings but nothing happens! please help

**Comment by HarutoHiroki** [comment]
why don't you try to do what the bot tells you to do before asking? Of course the bot wont work because you haven't set it up with !settings yet

**Comment by KuroDonut** [comment]
well i did then it gives my this weird message settings template|upload|current (file upload) then i type settings template it gives me a file what am i supposed to do with it??

**Comment by HarutoHiroki** [comment]
you download the file, edit it as you like then upload it like anyone would do
as for uploading just attach the file in discord with the command (prefix)settings upload

**Comment by KuroDonut** [comment]
I did it gives me an error

`(node:15940) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token | in JSON at position 66
    at JSON.parse (<anonymous>)
    at WriteStream.<anonymous> (C:\Users\Gamma\Desktop\Discord.js-Bot\commands\settings.js:24:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)`
