### ISSUE TITLE
bot starting error

### ISSUE THREAD

**Issue by ScchutzZ** [HarutoHiroki/Discord.js-Bot#13]
Hello, 
![indir](https://user-images.githubusercontent.com/10107035/88455397-a6a0a080-ce7d-11ea-91f0-cac2f08bb4d1.png)

How can I fix this error?

**Comment by HarutoHiroki** [comment]
my error, didnt delete old code, delete line 7 and 8 if you're still using the original code and everything should be fine

**Comment by HarutoHiroki** [comment]
I've pushed an update to fix this issue

**Comment by ScchutzZ** [comment]
> I've pushed an update to fix this issue

Thanks for your interest, the problem has been solved.
