### ISSUE TITLE
about settings

### ISSUE THREAD

**Issue by ScchutzZ** [HarutoHiroki/Discord.js-Bot#14]
![indir (1)](https://user-images.githubusercontent.com/10107035/88459678-cf399200-ce9f-11ea-952f-860e8d8cc459.png)
![indir (2)](https://user-images.githubusercontent.com/10107035/88459679-cfd22880-ce9f-11ea-91c8-af920391d05c.png)

I edited the settings but it still says so. Please run /settings to set up the bot first!

**Comment by HarutoHiroki** [comment]
remove comma after last object. would recommend you looking into how JSON works.
