### ISSUE TITLE
Wallpaper command has nsfw images

### ISSUE THREAD

**Issue by sbdh11** [HarutoHiroki/Discord.js-Bot#16]
Recently I was just spamming the wallpaper command (Neko's api) from my bot and I found some nsfw images which shouldn't supposed to be it. I saw the command in this repo so thought of making this Issue, Either allow that command for nsfw only channels or just delete that command

**Comment by HarutoHiroki** [comment]
I see, according to nekos.life docs this endpoint is supposed to be SFW so you should also tell the creator of the API too. I'll add the nsfw tag to the source code and upload it as a temp fix for now.
