### ISSUE TITLE
um.... I dont really like the settings thing.. Its too hard to explain to people how to use it..

### ISSUE THREAD

**Issue by SmugTheKiler** [HarutoHiroki/Discord.js-Bot#21]

**Comment by aididan20** [comment]
Download the file, edit the file, upload the file.

**Comment by HarutoHiroki** [comment]
there is always an option to code a dashboard (i found this nice example out there https://github.com/MrAugu/simple-discordjs-dashboard ) or to just remove the command and make multiple separate command to change each settings.
