### ISSUE TITLE
"findUser is not defined"

### ISSUE THREAD

**Issue by sn0wwfall** [HarutoHiroki/Discord.js-Bot#26]
(node:26680) UnhandledPromiseRejectionWarning: ReferenceError: findUser is not defined
    at C:\Users\Desktop\asdfohasdfiop\Discord.js-Bot-master\events\message.js:134:49
    at C:\Users\Desktop\asdfohasdfiop\Discord.js-Bot-master\node_modules\mongoose\lib\model.js:4845:18
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HarutoHiroki** [comment]
solved
