### ISSUE TITLE
Cannot Upload the file

### ISSUE THREAD

**Issue by Kizqn** [HarutoHiroki/Discord.js-Bot#29]
Done Downloading (node:15940) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token | in JSON at position 66 at JSON.parse (<anonymous>) at WriteStream.<anonymous> (C:\Users\Gamma\Desktop\Discord.js-Bot\commands\settings.js:24:36) at processTicksAndRejections (internal/process/task_queues.js:97:5) (node:15940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:15940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can u help with this??

**Comment by HarutoHiroki** [comment]
![image](https://user-images.githubusercontent.com/47408169/120927343-de69ad00-c70a-11eb-9786-a5d3696d18f5.png)

Please read the README.md
