### ISSUE TITLE
Bot loads up, but does not respond to any command.

### ISSUE THREAD

**Issue by MrFishy08** [HarutoHiroki/Discord.js-Bot#6]
I installed all the packages, I have all the files. When i type in node . it loads up properly with no problems, but when i go to my server (I made sure to give the bot every single permission) it does not respond to any command at all. Please help!

**Comment by MrFishy08** [comment]
Also i forgot to say, there are no errors in the console when trying to execute a command

**Comment by HarutoHiroki** [comment]
Have you set up the bot yet? Like the database and stuff with /settings?

**Comment by HarutoHiroki** [comment]
If you need further support feel free to shoot me an invite on discord
