### ISSUE TITLE
help

### ISSUE THREAD

**Issue by FrostyJack1** [HarutoHiroki/Discord.js-Bot#9]
dude i did what you said i put the file and in file i write a comment =settings upload
and nothing 
when i try running another command it says "first do /settings"

**Comment by FrostyJack1** [comment]
it shows me this error

(node:2876) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 178
    at JSON.parse (<anonymous>)
    at WriteStream.<anonymous> (D:\Documents\GitHub\PaperLaw\commands\settings.js:24:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FrostyJack1** [comment]
nvm fixed

**Comment by Kizqn** [comment]
Please help me how to fix!
